# generated by datamodel-codegen:
#   filename:  layout.json
#   timestamp: 2022-07-20T06:20:57+00:00

from __future__ import annotations
from typing import Dict, List, Optional
from pydantic import BaseModel, constr
from common import Arg
from base import MovaiBaseModel


class WidgetInst(BaseModel):
    Template: Optional[str] = None
    # Parameter: Optional[ArgSchema] = None
    Parameter: Optional[Dict[constr(regex=r"^[a-zA-Z0-9_]+$"), Arg]] = None


class Layout(MovaiBaseModel):
    Icon: Optional[
        str
    ] = None  # currently this field is deprecated, maybe will be in used in the future
    DashboardTitle: Optional[
        str
    ] = None  # currently this field is deprecated, maybe will be in used in the future
    Styles: Optional[str] = None
    WidgetInst: Optional[
        Dict[
            constr(
                regex=r"^(Button|Selector|Input|Label|Divider|Joystick|VideoPanel|Toggle|Scene|StartFlow)[0-9]*$"
            ),
            WidgetInst,
        ]
    ] = None
    LayoutColors: Optional[List] = None

    # https: // movai.atlassian.net / browse / BP - 749
    # missing fields:
    # allLayouts
    # layoutEvents

    class Meta:
        model_key_prefix = "Layout"


if __name__ == "__main__":
    layout = Layout(**{
        "Layout": {
            "tugbot": {
                "DashboardTitle": "",
                "Icon": "",
                "Info": "",
                "Label": "tugbot",
                "LastUpdate": "13/10/2020 at 17:46:50",
                "LayoutColors": [],
                "Styles": "",
                "User": "",
                "Version": "",
                "VersionDelta": {},
                "WidgetInst": {
                    "Button": {
                        "Parameter": {
                            "arguments": {
                                "Value": "trajectory_1/end"
                            },
                            "cloudFunction": {
                                "Value": "transition_button"
                            },
                            "color": {
                                "Value": "inherit"
                            },
                            "height": {
                                "Value": 5
                            },
                            "i": {
                                "Value": "1"
                            },
                            "minHeight": {
                                "Value": 5
                            },
                            "minWidth": {
                                "Value": 1
                            },
                            "text": {
                                "Value": "Press Here"
                            },
                            "variant": {
                                "Value": "contained"
                            },
                            "width": {
                                "Value": 3
                            },
                            "x": {
                                "Value": 4
                            },
                            "y": {
                                "Value": 0
                            }
                        },
                        "Template": "Button"
                    },
                    "Button1": {
                        "Parameter": {
                            "arguments": {
                                "Value": "goto_drop"
                            },
                            "cloudFunction": {
                                "Value": "run_state"
                            },
                            "color": {
                                "Value": "primary"
                            },
                            "height": {
                                "Value": 5
                            },
                            "i": {
                                "Value": "3"
                            },
                            "minHeight": {
                                "Value": 5
                            },
                            "minWidth": {
                                "Value": 1
                            },
                            "text": {
                                "Value": "Recovery"
                            },
                            "variant": {
                                "Value": "contained"
                            },
                            "width": {
                                "Value": 2
                            },
                            "x": {
                                "Value": 7
                            },
                            "y": {
                                "Value": 5
                            }
                        },
                        "Template": "Button"
                    },
                    "Button2": {
                        "Parameter": {
                            "arguments": {
                                "Value": "recovery"
                            },
                            "cloudFunction": {
                                "Value": "run_state"
                            },
                            "color": {
                                "Value": "primary"
                            },
                            "height": {
                                "Value": 5
                            },
                            "i": {
                                "Value": "4"
                            },
                            "minHeight": {
                                "Value": 5
                            },
                            "minWidth": {
                                "Value": 1
                            },
                            "text": {
                                "Value": "Respawn Node"
                            },
                            "variant": {
                                "Value": "contained"
                            },
                            "width": {
                                "Value": 3
                            },
                            "x": {
                                "Value": 4
                            },
                            "y": {
                                "Value": 5
                            }
                        },
                        "Template": "Button"
                    },
                    "Button3": {
                        "Parameter": {
                            "arguments": {
                                "Value": "dock__dock"
                            },
                            "cloudFunction": {
                                "Value": "run_state"
                            },
                            "color": {
                                "Value": "primary"
                            },
                            "height": {
                                "Value": 5
                            },
                            "i": {
                                "Value": "5"
                            },
                            "minHeight": {
                                "Value": 5
                            },
                            "minWidth": {
                                "Value": 1
                            },
                            "text": {
                                "Value": "align"
                            },
                            "variant": {
                                "Value": "contained"
                            },
                            "width": {
                                "Value": 6
                            },
                            "x": {
                                "Value": 3
                            },
                            "y": {
                                "Value": 10
                            }
                        },
                        "Template": "Button"
                    },
                    "Joystick": {
                        "Parameter": {
                            "endPoint": {
                                "Value": "joystick"
                            },
                            "height": {
                                "Value": 10
                            },
                            "i": {
                                "Value": "0"
                            },
                            "ip": {
                                "Value": "10.10.1.207"
                            },
                            "minHeight": {
                                "Value": 7
                            },
                            "minWidth": {
                                "Value": 2
                            },
                            "port": {
                                "Value": "7000"
                            },
                            "rate": {
                                "Value": 20
                            },
                            "robotName": {
                                "Value": "robotA"
                            },
                            "width": {
                                "Value": 4
                            },
                            "x": {
                                "Value": 0
                            },
                            "y": {
                                "Value": 0
                            }
                        },
                        "Template": "Joystick"
                    },
                    "StartFlow": {
                        "Parameter": {
                            "action": {
                                "Value": "Start"
                            },
                            "flowID": {
                                "Value": "tugbot_lab_december"
                            },
                            "height": {
                                "Value": 5
                            },
                            "i": {
                                "Value": "2"
                            },
                            "minHeight": {
                                "Value": 4
                            },
                            "minWidth": {
                                "Value": 2
                            },
                            "robotID": {
                                "Value": "d4f9a44d939c4331b7c3fd704220b6c0"
                            },
                            "width": {
                                "Value": 3
                            },
                            "x": {
                                "Value": 0
                            },
                            "y": {
                                "Value": 10
                            }
                        },
                        "Template": "StartFlow"
                    },
                    "Toggle": {
                        "Parameter": {
                            "cloudFunction": {
                                "Value": "toggle"
                            },
                            "height": {
                                "Value": 5
                            },
                            "i": {
                                "Value": "6"
                            },
                            "minHeight": {
                                "Value": 5
                            },
                            "minWidth": {
                                "Value": 2
                            },
                            "offText": {
                                "Value": "Stop"
                            },
                            "onText": {
                                "Value": "Start"
                            },
                            "robotName": {
                                "Value": ""
                            },
                            "subKey": {
                                "Value": "robot"
                            },
                            "varName": {
                                "Value": "auto"
                            },
                            "width": {
                                "Value": 2
                            },
                            "x": {
                                "Value": 7
                            },
                            "y": {
                                "Value": 0
                            }
                        },
                        "Template": "Toggle"
                    }
                }
            }
        }
    })

    pk = layout.save()

    print(Layout.select(ids=[pk]))

