name: "CI - On main/dev/release branches"
on:
  pull_request:
    branches:
      - dev
      - main
      - 'releases/**'
    paths-ignore:
      - '.bumpversion.cfg'
      - 'setup.py'
jobs:
  CI:
    uses: MOV-AI/.github/.github/workflows/py-workflow.yml@v1
    with:
      deploy: 'false'
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  Install-Tests:
    runs-on: ubuntu-20.04
    needs:  [CI]
    container:
      image: registry.cloud.mov.ai/devops/movai-base-noetic:v1.4.5
      options: --user movai
      credentials:
        username: ${{secrets.registry_user}}
        password: ${{secrets.registry_password}}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          submodules: recursive

      - name: Download generated python artifact
        uses: actions/download-artifact@v2
        with:
          name: packages
          path: dist

      - name: Install pip
        run: |
          python3 -m pip install --no-cache-dir \
          --index-url="https://artifacts.cloud.mov.ai/repository/pypi-experimental/simple" \
          --extra-index-url https://pypi.org/simple \
          ./dist/*.whl


