name: "CI - On main/dev/release branches"
on:
  pull_request:
    branches:
      - '**/**'
jobs:
  CI:
    uses: MOV-AI/.github/.github/workflows/py-workflow.yml@fix-new-code-on-branch
    with:
      deploy: false
      with_docs: true
    secrets:
      auto_commit_user: ${{ secrets.RAISE_BOT_COMMIT_USER }}
      auto_commit_mail: ${{ secrets.RAISE_BOT_COMMIT_MAIL }}
      auto_commit_password: ${{ secrets.RAISE_BOT_COMMIT_PASSWORD }}
      registry_user: ${{ secrets.PORTUS_APP_USER }}
      registry_password: ${{ secrets.PORTUS_APP_TOKEN }}
      nexus_publisher_user: ${{ secrets.NEXUS_PUBLISHER_USR }}
      nexus_publisher_password: ${{ secrets.NEXUS_PUBLISHER_PWD }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  Install-Tests-Noetic:
    runs-on: ubuntu-20.04
    needs:  [CI]
    container:
      image: registry.cloud.mov.ai/devops/movai-base-noetic:v1.4.5
      options: --user root
      credentials:
        username: ${{ secrets.PORTUS_APP_USER }}
        password: ${{ secrets.PORTUS_APP_TOKEN }}

    steps:
      - name: Download generated python artifact
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: dist

      - name: Install pip
        run: |
          python3 -m pip install --no-cache-dir \
          --index-url="https://artifacts.cloud.mov.ai/repository/pypi-experimental/simple" \
          --extra-index-url https://pypi.org/simple \
          ./dist/*.whl
